import { LocateFixed, ShieldCheck, Siren, TimerReset } from "lucide-react";

import { Card, CardContent } from "@/components/ui/card";
import { DetectionStatusBadge } from "@/features/detections/components/detection-status-badge";
import { EmptyState } from "@/components/shared/empty-state";
import type { LiveEvent } from "@/types";

interface DetectionDetailPanelProps {
  detection: LiveEvent | null;
}

export function DetectionDetailPanel({
  detection,
}: DetectionDetailPanelProps) {
  if (!detection) {
    return (
      <EmptyState
        description="Select a detection to review confidence, coordinates, operational status, and response context."
        title="No detection selected"
      />
    );
  }

  return (
    <Card className="border-border-subtle/80 bg-surface/88">
      <CardContent className="space-y-5 p-5 sm:p-6">
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-[0.24em] text-brand-secondary">
            Detection detail
          </p>
          <h2 className="text-xl font-semibold text-text-primary">
            {detection.id}
          </h2>
          <p className="text-sm leading-7 text-text-muted">{detection.message}</p>
        </div>

        <div className="flex flex-wrap gap-2">
          <DetectionStatusBadge kind="type" value={detection.type} />
          <DetectionStatusBadge kind="severity" value={detection.severity} />
          <DetectionStatusBadge kind="status" value={detection.status} />
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <div className="rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-text-muted">
              Confidence
            </p>
            <p className="mt-2 text-2xl font-semibold text-text-primary">
              {detection.confidence}%
            </p>
            <p className="mt-2 text-sm text-text-muted">
              Confidence score generated by the current detection model.
            </p>
          </div>
          <div className="rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-text-muted">
              Zone
            </p>
            <p className="mt-2 text-2xl font-semibold text-text-primary">
              {detection.zone}
            </p>
            <p className="mt-2 text-sm text-text-muted">
              Operational sector currently associated with this signal.
            </p>
          </div>
        </div>

        <div className="space-y-3 rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
          <div className="flex items-center gap-2 text-sm font-medium text-text-primary">
            <LocateFixed className="h-4 w-4 text-brand-secondary" />
            Coordinates
          </div>
          <p className="text-sm text-text-muted">{detection.coordinates}</p>
        </div>

        <div className="space-y-3 rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
          <div className="flex items-center gap-2 text-sm font-medium text-text-primary">
            <TimerReset className="h-4 w-4 text-brand-secondary" />
            Exact timestamp
          </div>
          <p className="text-sm text-text-muted">{detection.timestamp}</p>
        </div>

        <div className="grid gap-4">
          <div className="rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
            <div className="flex items-center gap-2 text-sm font-medium text-text-primary">
              <ShieldCheck className="h-4 w-4 text-brand-secondary" />
              Response note
            </div>
            <p className="mt-2 text-sm leading-6 text-text-muted">
              Response workflow placeholder: assign ranger escalation, confirm
              visual evidence, and log analyst notes for incident continuity.
            </p>
          </div>
          <div className="rounded-2xl border border-border-subtle/80 bg-canvas/45 p-4">
            <div className="flex items-center gap-2 text-sm font-medium text-text-primary">
              <Siren className="h-4 w-4 text-brand-secondary" />
              Related alert context
            </div>
            <p className="mt-2 text-sm leading-6 text-text-muted">
              Related incident placeholder: this detection can be linked to a
              future alert or reporting workflow once backend case data is
              available.
            </p>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
